const TAG_DEFINITIONS = [
  // --- Wound type ---
  { name: "blood", description: "Does the image contain blood?" },
  { name: "bleeding", description: "Does the image contain bleeding?" },
  { name: "hemorrhage", description: "Does the image contain hemorrhage?" },
  { name: "laceration", description: "Does the image contain laceration?" },
  { name: "abrasion", description: "Does the image contain abrasion?" },
  { name: "puncture-wound", description: "Does the image contain puncture wound?" },
  { name: "cut", description: "Does the image contain cut?" },
  { name: "burn", description: "Does the image contain burn?" },
  { name: "avulsion", description: "Does the image contain avulsion?" },

  // --- Bleeding severity ---
  { name: "blood-pooling", description: "Does the image contain blood pooling?" },
  { name: "blood-soaked-bandage", description: "Does the image contain blood soaked bandage?" },

  // --- Consciousness ---
  { name: "unconscious", description: "Does the image contain unconscious?" },
  { name: "unresponsive", description: "Does the image contain unresponsive?" },
  { name: "altered-mental-status", description: "Does the image contain altered mental status?" },
  { name: "confusion", description: "Does the image contain confusion?" },

  // --- Skin signs (shock indicators) ---
  { name: "pale-skin", description: "Does the image contain pale skin?" },
  { name: "cyanosis", description: "Does the image contain cyanosis?" },
  { name: "diaphoresis", description: "Does the image contain diaphoresis?" },

  // --- Body location ---
  { name: "head", description: "Does the image contain head?" },
  { name: "neck", description: "Does the image contain neck?" },
  { name: "chest", description: "Does the image contain chest?" },
  { name: "abdomen", description: "Does the image contain abdomen?" },
  { name: "arm", description: "Does the image contain arm?" },
  { name: "leg", description: "Does the image contain leg?" },

  // --- Mechanism ---
  { name: "vehicle-collision", description: "Does the image contain vehicle collision?" },
  { name: "fall-from-height", description: "Does the image contain fall from height?" },
  { name: "stab-wound", description: "Does the image contain stab wound?" },
  { name: "gunshot-wound", description: "Does the image contain gunshot wound?" },

  // --- Already treated (de-escalates severity) ---
  { name: "splint", description: "Does the image contain splint?" },
  { name: "pressure-dressing", description: "Does the image contain pressure dressing?" },
  { name: "cervical-collar", description: "Does the image contain cervical collar?" },

  { name: "incision", description: "Does the image contain incision?" },
  { name: "open-wound", description: "Does the image contain open wound?" },
  { name: "gash", description: "Does the image contain gash?" },
  { name: "road-rash", description: "Does the image contain road rash?" },
  { name: "skin-tear", description: "Does the image contain skin tear?" },
  { name: "swelling", description: "Does the image contain swelling?" },
  { name: "edema", description: "Does the image contain edema?" },
  { name: "bruise", description: "Does the image contain bruise?" },
  { name: "contusion", description: "Does the image contain contusion?" },
  { name: "hematoma", description: "Does the image contain hematoma?" },
  { name: "ecchymosis", description: "Does the image contain ecchymosis?" },
  { name: "discoloration", description: "Does the image contain discoloration?" },
  { name: "fracture", description: "Does the image contain fracture?" },
  { name: "bone", description: "Does the image contain bone?" },
  { name: "deformity", description: "Does the image contain deformity?" },
  { name: "angulation", description: "Does the image contain angulation?" },
  { name: "dislocation", description: "Does the image contain dislocation?" },
  { name: "cast", description: "Does the image contain cast?" },
  { name: "scald", description: "Does the image contain scald?" },
  { name: "blister", description: "Does the image contain blister?" },
  { name: "redness", description: "Does the image contain redness?" },
  { name: "thermal-injury", description: "Does the image contain thermal injury?" },
  { name: "lying-down", description: "Does the image contain lying down?" },
  { name: "supine", description: "Does the image contain supine?" },
  { name: "prone", description: "Does the image contain prone?" },
  { name: "eyes-closed", description: "Does the image contain eyes closed?" },
  { name: "limp", description: "Does the image contain limp?" },
  { name: "face", description: "Does the image contain face?" },
  { name: "back", description: "Does the image contain back?" },
  { name: "hand", description: "Does the image contain hand?" },
  { name: "foot", description: "Does the image contain foot?" },
  { name: "shoulder", description: "Does the image contain shoulder?" },
  { name: "knee", description: "Does the image contain knee?" },
  { name: "wound-bed", description: "Does the image contain wound bed?" },
  { name: "eschar", description: "Does the image contain eschar?" },
  { name: "necrosis", description: "Does the image contain necrosis?" },
  { name: "tissue-damage", description: "Does the image contain tissue damage?" },
  { name: "muscle-exposure", description: "Does the image contain muscle exposure?" },
  { name: "tendon-exposure", description: "Does the image contain tendon exposure?" },
  { name: "bone-exposure", description: "Does the image contain bone exposure?" },
  { name: "degloving", description: "Does the image contain degloving?" },
  { name: "amputation", description: "Does the image contain amputation?" },
  { name: "partial-amputation", description: "Does the image contain partial amputation?" },
  { name: "crush-injury", description: "Does the image contain crush injury?" },
  { name: "compartment-syndrome", description: "Does the image contain compartment syndrome?" },
  { name: "impaled-object", description: "Does the image contain impaled object?" },
  { name: "foreign-body", description: "Does the image contain foreign body?" },
  { name: "debris-in-wound", description: "Does the image contain debris in wound?" },
  { name: "wound-drainage", description: "Does the image contain wound drainage?" },
  { name: "purulent-discharge", description: "Does the image contain purulent discharge?" },
  { name: "infection", description: "Does the image contain infection?" },
  { name: "cellulitis", description: "Does the image contain cellulitis?" },
  { name: "abscess", description: "Does the image contain abscess?" },
  { name: "erythema", description: "Does the image contain erythema?" },
  { name: "warmth", description: "Does the image contain warmth?" },
  { name: "crepitus", description: "Does the image contain crepitus?" },
  { name: "flail-chest", description: "Does the image contain flail chest?" },
  { name: "pneumothorax", description: "Does the image contain pneumothorax?" },
  { name: "rib-fracture", description: "Does the image contain rib fracture?" },
  { name: "clavicle-fracture", description: "Does the image contain clavicle fracture?" },
  { name: "femur-fracture", description: "Does the image contain femur fracture?" },
  { name: "tibia-fracture", description: "Does the image contain tibia fracture?" },
  { name: "radius-fracture", description: "Does the image contain radius fracture?" },
  { name: "ulna-fracture", description: "Does the image contain ulna fracture?" },
  { name: "humerus-fracture", description: "Does the image contain humerus fracture?" },
  { name: "pelvis-fracture", description: "Does the image contain pelvis fracture?" },
  { name: "spinal-injury", description: "Does the image contain spinal injury?" },
  { name: "backboard", description: "Does the image contain backboard?" },
  { name: "traction-splint", description: "Does the image contain traction splint?" },
  { name: "air-splint", description: "Does the image contain air splint?" },
  { name: "wound-packing", description: "Does the image contain wound packing?" },
  { name: "hemostatic-dressing", description: "Does the image contain hemostatic dressing?" },
  { name: "iv-line", description: "Does the image contain iv line?" },
  { name: "oxygen-mask", description: "Does the image contain oxygen mask?" },
  { name: "nasal-cannula", description: "Does the image contain nasal cannula?" },
  { name: "bag-valve-mask", description: "Does the image contain bag valve mask?" },
  { name: "intubation", description: "Does the image contain intubation?" },
  { name: "chest-seal", description: "Does the image contain chest seal?" },
  { name: "needle-decompression", description: "Does the image contain needle decompression?" },
  { name: "patient-on-ground", description: "Does the image contain patient on ground?" },
  { name: "patient-seated", description: "Does the image contain patient seated?" },
  { name: "patient-standing", description: "Does the image contain patient standing?" },
  { name: "bystander-assisting", description: "Does the image contain bystander assisting?" },
  { name: "crowded-scene", description: "Does the image contain crowded scene?" },
  { name: "motorcycle-accident", description: "Does the image contain motorcycle accident?" },
  { name: "pedestrian-struck", description: "Does the image contain pedestrian struck?" },
  { name: "industrial-accident", description: "Does the image contain industrial accident?" },
  { name: "sports-injury", description: "Does the image contain sports injury?" },
  { name: "assault", description: "Does the image contain assault?" },
  { name: "blast-injury", description: "Does the image contain blast injury?" },
  { name: "crush", description: "Does the image contain crush?" },
  { name: "drowning", description: "Does the image contain drowning?" },
  { name: "hanging", description: "Does the image contain hanging?" },
  { name: "overdose", description: "Does the image contain overdose?" },
  { name: "seizure", description: "Does the image contain seizure?" },
  { name: "stroke-signs", description: "Does the image contain stroke signs?" },
  { name: "agitation", description: "Does the image contain agitation?" },
  { name: "combative-patient", description: "Does the image contain combative patient?" },
  { name: "mottled-skin", description: "Does the image contain mottled skin?" },
  { name: "flushed-skin", description: "Does the image contain flushed skin?" },
  { name: "jaundice", description: "Does the image contain jaundice?" },
  { name: "rash", description: "Does the image contain rash?" },
  { name: "petechiae", description: "Does the image contain petechiae?" },
  { name: "purpura", description: "Does the image contain purpura?" },
  {
    name: "capillary-refill-delayed",
    description: "Does the image contain capillary refill delayed?",
  },
  {
    name: "jugular-vein-distension",
    description: "Does the image contain jugular vein distension?",
  },
  { name: "tracheal-deviation", description: "Does the image contain tracheal deviation?" },
  { name: "unequal-pupils", description: "Does the image contain unequal pupils?" },
  { name: "dilated-pupils", description: "Does the image contain dilated pupils?" },
  { name: "constricted-pupils", description: "Does the image contain constricted pupils?" },
  { name: "blood-in-eye", description: "Does the image contain blood in eye?" },
  { name: "facial-laceration", description: "Does the image contain facial laceration?" },
  { name: "scalp-laceration", description: "Does the image contain scalp laceration?" },
  { name: "ear-injury", description: "Does the image contain ear injury?" },
  { name: "nose-bleed", description: "Does the image contain nose bleed?" },
  { name: "epistaxis", description: "Does the image contain epistaxis?" },
  { name: "dental-injury", description: "Does the image contain dental injury?" },
  { name: "jaw-injury", description: "Does the image contain jaw injury?" },
  { name: "tongue-injury", description: "Does the image contain tongue injury?" },
  { name: "throat-injury", description: "Does the image contain throat injury?" },
  { name: "laryngeal-trauma", description: "Does the image contain laryngeal trauma?" },
  { name: "chest-wall-bruising", description: "Does the image contain chest wall bruising?" },
  { name: "flail-segment", description: "Does the image contain flail segment?" },
  { name: "sucking-chest-wound", description: "Does the image contain sucking chest wound?" },
  { name: "abdominal-distension", description: "Does the image contain abdominal distension?" },
  { name: "evisceration", description: "Does the image contain evisceration?" },
  { name: "pelvic-instability", description: "Does the image contain pelvic instability?" },
  { name: "priapism", description: "Does the image contain priapism?" },
  { name: "genital-injury", description: "Does the image contain genital injury?" },
  {
    name: "lower-extremity-swelling",
    description: "Does the image contain lower extremity swelling?",
  },
  {
    name: "upper-extremity-swelling",
    description: "Does the image contain upper extremity swelling?",
  },
  { name: "joint-effusion", description: "Does the image contain joint effusion?" },
  { name: "hemarthrosis", description: "Does the image contain hemarthrosis?" },
  { name: "knee-dislocation", description: "Does the image contain knee dislocation?" },
  { name: "hip-dislocation", description: "Does the image contain hip dislocation?" },
  { name: "shoulder-dislocation", description: "Does the image contain shoulder dislocation?" },
  { name: "elbow-dislocation", description: "Does the image contain elbow dislocation?" },
  { name: "ankle-fracture", description: "Does the image contain ankle fracture?" },
  { name: "wrist-fracture", description: "Does the image contain wrist fracture?" },
  { name: "finger-fracture", description: "Does the image contain finger fracture?" },
  { name: "toe-fracture", description: "Does the image contain toe fracture?" },
  { name: "nail-avulsion", description: "Does the image contain nail avulsion?" },
  { name: "subungual-hematoma", description: "Does the image contain subungual hematoma?" },
  { name: "ring-avulsion", description: "Does the image contain ring avulsion?" },
  { name: "degloving-finger", description: "Does the image contain degloving finger?" },
  { name: "burn-blister", description: "Does the image contain burn blister?" },
  { name: "partial-thickness-burn", description: "Does the image contain partial thickness burn?" },
  { name: "full-thickness-burn", description: "Does the image contain full thickness burn?" },
  { name: "chemical-burn", description: "Does the image contain chemical burn?" },
  { name: "electrical-burn", description: "Does the image contain electrical burn?" },
  { name: "inhalation-injury", description: "Does the image contain inhalation injury?" },
  { name: "singed-eyebrows", description: "Does the image contain singed eyebrows?" },
  { name: "singed-nasal-hair", description: "Does the image contain singed nasal hair?" },
  { name: "circumferential-burn", description: "Does the image contain circumferential burn?" },
  { name: "burn-eschar", description: "Does the image contain burn eschar?" },
  { name: "fluid-resuscitation", description: "Does the image contain fluid resuscitation?" },
  { name: "foley-catheter", description: "Does the image contain foley catheter?" },
  { name: "nasogastric-tube", description: "Does the image contain nasogastric tube?" },
  { name: "chest-tube", description: "Does the image contain chest tube?" },
  { name: "pacemaker", description: "Does the image contain pacemaker?" },
  { name: "defibrillator-pads", description: "Does the image contain defibrillator pads?" },
  { name: "cpr-in-progress", description: "Does the image contain cpr in progress?" },
  { name: "ppe-worn", description: "Does the image contain ppe worn?" },
  { name: "blood-on-gloves", description: "Does the image contain blood on gloves?" },
  { name: "blood-on-clothing", description: "Does the image contain blood on clothing?" },
  { name: "blood-spatter", description: "Does the image contain blood spatter?" },
  { name: "blood-trail", description: "Does the image contain blood trail?" },
];
export default TAG_DEFINITIONS;

